INSERT INTO DEPARTMENTS (DEPID,NAME) VALUES (1,'Management');
INSERT INTO DEPARTMENTS (NAME,DEPID) VALUES ('Administration',2);

INSERT INTO DEPARTMENTS VALUES (3,'Technological');
INSERT INTO DEPARTMENTS VALUES (4,'Support');

INSERT INTO EMPLOYEES (EMPLOYEEID,DEPID,SURNAME,NAME,BIRTHDATE,HEIGHT,BOSSID) VALUES (1,2,'Smith','John','17-4-1997',1.87,4);
INSERT INTO EMPLOYEES (EMPLOYEEID,DEPID,SURNAME,NAME,BIRTHDATE,HEIGHT,BOSSID) VALUES (2,1,'J','Anju','14-4-1997',1.58,5);




SELECT * FROM DEPARTMENTS;

SELECT * FROM DEPARTMENTS
ORDER BY DEPID DESC;